/* src/objfw-defs.h.  Generated from objfw-defs.h.in by configure.  */
#define OF_APPLE_RUNTIME 1
/* #undef OF_BIG_ENDIAN */
/* #undef OF_FLOAT_BIG_ENDIAN */
#define OF_HAVE_ATOMIC_OPS 1
#define OF_HAVE_BUILTIN_BSWAP16 1
#define OF_HAVE_BUILTIN_BSWAP32 1
#define OF_HAVE_BUILTIN_BSWAP64 1
#define OF_HAVE_CHMOD 1
#define OF_HAVE_CHOWN 1
#define OF_HAVE_FILES 1
/* #undef OF_HAVE_FORWARDING_TARGET_FOR_SELECTOR */
#define OF_HAVE_GCC_ATOMIC_OPS 1
#define OF_HAVE_LINK 1
#define OF_HAVE_MAX_ALIGN_T 1
#define OF_HAVE_NETINET_IN_H 1
#define OF_HAVE_OSATOMIC 1
/* #undef OF_HAVE_OSATOMIC_64 */
#define OF_HAVE_PIPE 1
#define OF_HAVE_PLUGINS 1
#define OF_HAVE_PROCESSES 1
#define OF_HAVE_PTHREADS 1
/* #undef OF_HAVE_PTHREAD_SPINLOCKS */
#define OF_HAVE_RECURSIVE_PTHREAD_MUTEXES 1
#define OF_HAVE_SCHED_YIELD 1
#define OF_HAVE_SOCKETS 1
/* #undef OF_HAVE_STDNORETURN */
#define OF_HAVE_SYMLINK 1
#define OF_HAVE_SYS_SOCKET_H 1
#define OF_HAVE_THREADS 1
#define OF_HAVE___THREAD 1
#define OF_HAVE__THREAD_LOCAL 1
/* #undef OF_NINTENDO_DS */
/* #undef OF_OBJFW_RUNTIME */
#define OF_UNIVERSAL 1
/* #undef SIZE_MAX */
